// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByVideo = `-- name: CountCommentsByVideo :one
SELECT COUNT(*) FROM comments WHERE video_id = $1 AND parent_id IS NULL
`

func (q *Queries) CountCommentsByVideo(ctx context.Context, videoID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByVideo, videoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    video_id, user_id, content, timestamp_seconds, parent_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, video_id, user_id, content, timestamp_seconds, parent_id, created_at, updated_at
`

type CreateCommentParams struct {
	VideoID          uuid.UUID   `json:"video_id"`
	UserID           uuid.UUID   `json:"user_id"`
	Content          string      `json:"content"`
	TimestampSeconds *int32      `json:"timestamp_seconds"`
	ParentID         pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.VideoID,
		arg.UserID,
		arg.Content,
		arg.TimestampSeconds,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Content,
		&i.TimestampSeconds,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, video_id, user_id, content, timestamp_seconds, parent_id, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Content,
		&i.TimestampSeconds,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentMarkers = `-- name: GetCommentMarkers :many
SELECT 
    timestamp_seconds,
    COUNT(*) as count
FROM comments
WHERE video_id = $1 AND timestamp_seconds IS NOT NULL
GROUP BY timestamp_seconds
ORDER BY timestamp_seconds ASC
`

type GetCommentMarkersRow struct {
	TimestampSeconds *int32 `json:"timestamp_seconds"`
	Count            int64  `json:"count"`
}

func (q *Queries) GetCommentMarkers(ctx context.Context, videoID uuid.UUID) ([]GetCommentMarkersRow, error) {
	rows, err := q.db.Query(ctx, getCommentMarkers, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentMarkersRow{}
	for rows.Next() {
		var i GetCommentMarkersRow
		if err := rows.Scan(&i.TimestampSeconds, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentWithAuthor = `-- name: GetCommentWithAuthor :one
SELECT 
    c.id, c.video_id, c.user_id, c.content, c.timestamp_seconds, c.parent_id, c.created_at, c.updated_at,
    u.username as author_username,
    u.avatar_filename as author_avatar,
    v.uploaded_by as video_owner_id
FROM comments c
JOIN users u ON c.user_id = u.id
JOIN videos v ON c.video_id = v.id
WHERE c.id = $1
`

type GetCommentWithAuthorRow struct {
	ID               uuid.UUID   `json:"id"`
	VideoID          uuid.UUID   `json:"video_id"`
	UserID           uuid.UUID   `json:"user_id"`
	Content          string      `json:"content"`
	TimestampSeconds *int32      `json:"timestamp_seconds"`
	ParentID         pgtype.UUID `json:"parent_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	AuthorUsername   string      `json:"author_username"`
	AuthorAvatar     *string     `json:"author_avatar"`
	VideoOwnerID     uuid.UUID   `json:"video_owner_id"`
}

func (q *Queries) GetCommentWithAuthor(ctx context.Context, id uuid.UUID) (GetCommentWithAuthorRow, error) {
	row := q.db.QueryRow(ctx, getCommentWithAuthor, id)
	var i GetCommentWithAuthorRow
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Content,
		&i.TimestampSeconds,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorAvatar,
		&i.VideoOwnerID,
	)
	return i, err
}

const listCommentsByVideo = `-- name: ListCommentsByVideo :many
SELECT 
    c.id, c.video_id, c.user_id, c.content, c.timestamp_seconds, c.parent_id, c.created_at, c.updated_at,
    u.username as author_username,
    u.avatar_filename as author_avatar,
    (SELECT COUNT(*) FROM comments r WHERE r.parent_id = c.id) as reply_count
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.video_id = $1 AND c.parent_id IS NULL
ORDER BY
    CASE WHEN $2 = 'newest' THEN c.created_at END DESC,
    CASE WHEN $2 = 'oldest' THEN c.created_at END ASC,
    CASE WHEN $2 = 'timestamp' THEN c.timestamp_seconds END ASC NULLS LAST,
    c.created_at DESC
LIMIT $3 OFFSET $4
`

type ListCommentsByVideoParams struct {
	VideoID uuid.UUID   `json:"video_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListCommentsByVideoRow struct {
	ID               uuid.UUID   `json:"id"`
	VideoID          uuid.UUID   `json:"video_id"`
	UserID           uuid.UUID   `json:"user_id"`
	Content          string      `json:"content"`
	TimestampSeconds *int32      `json:"timestamp_seconds"`
	ParentID         pgtype.UUID `json:"parent_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	AuthorUsername   string      `json:"author_username"`
	AuthorAvatar     *string     `json:"author_avatar"`
	ReplyCount       int64       `json:"reply_count"`
}

func (q *Queries) ListCommentsByVideo(ctx context.Context, arg ListCommentsByVideoParams) ([]ListCommentsByVideoRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByVideo,
		arg.VideoID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByVideoRow{}
	for rows.Next() {
		var i ListCommentsByVideoRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.UserID,
			&i.Content,
			&i.TimestampSeconds,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepliesByComment = `-- name: ListRepliesByComment :many
SELECT 
    c.id, c.video_id, c.user_id, c.content, c.timestamp_seconds, c.parent_id, c.created_at, c.updated_at,
    u.username as author_username,
    u.avatar_filename as author_avatar
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.parent_id = $1
ORDER BY c.created_at ASC
`

type ListRepliesByCommentRow struct {
	ID               uuid.UUID   `json:"id"`
	VideoID          uuid.UUID   `json:"video_id"`
	UserID           uuid.UUID   `json:"user_id"`
	Content          string      `json:"content"`
	TimestampSeconds *int32      `json:"timestamp_seconds"`
	ParentID         pgtype.UUID `json:"parent_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	AuthorUsername   string      `json:"author_username"`
	AuthorAvatar     *string     `json:"author_avatar"`
}

func (q *Queries) ListRepliesByComment(ctx context.Context, parentID pgtype.UUID) ([]ListRepliesByCommentRow, error) {
	rows, err := q.db.Query(ctx, listRepliesByComment, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepliesByCommentRow{}
	for rows.Next() {
		var i ListRepliesByCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.UserID,
			&i.Content,
			&i.TimestampSeconds,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments SET
    content = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, video_id, user_id, content, timestamp_seconds, parent_id, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Content,
		&i.TimestampSeconds,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
