"""add storage_path to video model

Revision ID: 8b56becc716a
Revises: 56dc9005c8c3
Create Date: 2025-12-22 00:27:04.517960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b56becc716a'
down_revision: Union[str, None] = '56dc9005c8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('storage_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'storage_path')
    # ### end Alembic commands ###
