// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfig = `-- name: GetConfig :one
SELECT id, max_file_size_bytes, weekly_upload_limit_bytes, video_storage_path, use_gpu_transcoding, gpu_device_id, nvenc_preset, nvenc_cq, nvenc_rate_control, nvenc_max_bitrate, nvenc_buffer_size, cpu_preset, cpu_crf, max_resolution, audio_bitrate, transcode_preset_mode, video_output_format, updated_at, updated_by FROM config WHERE id = 1
`

func (q *Queries) GetConfig(ctx context.Context) (Config, error) {
	row := q.db.QueryRow(ctx, getConfig)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.MaxFileSizeBytes,
		&i.WeeklyUploadLimitBytes,
		&i.VideoStoragePath,
		&i.UseGpuTranscoding,
		&i.GpuDeviceID,
		&i.NvencPreset,
		&i.NvencCq,
		&i.NvencRateControl,
		&i.NvencMaxBitrate,
		&i.NvencBufferSize,
		&i.CpuPreset,
		&i.CpuCrf,
		&i.MaxResolution,
		&i.AudioBitrate,
		&i.TranscodePresetMode,
		&i.VideoOutputFormat,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateConfig = `-- name: UpdateConfig :one
UPDATE config SET
    max_file_size_bytes = COALESCE($1, max_file_size_bytes),
    weekly_upload_limit_bytes = COALESCE($2, weekly_upload_limit_bytes),
    video_storage_path = COALESCE(NULLIF($3, ''), video_storage_path),
    use_gpu_transcoding = COALESCE($4, use_gpu_transcoding),
    gpu_device_id = COALESCE($5, gpu_device_id),
    nvenc_preset = COALESCE(NULLIF($6, ''), nvenc_preset),
    nvenc_cq = COALESCE($7, nvenc_cq),
    nvenc_rate_control = COALESCE(NULLIF($8, ''), nvenc_rate_control),
    nvenc_max_bitrate = COALESCE(NULLIF($9, ''), nvenc_max_bitrate),
    nvenc_buffer_size = COALESCE(NULLIF($10, ''), nvenc_buffer_size),
    cpu_preset = COALESCE(NULLIF($11, ''), cpu_preset),
    cpu_crf = COALESCE($12, cpu_crf),
    max_resolution = COALESCE(NULLIF($13, ''), max_resolution),
    audio_bitrate = COALESCE(NULLIF($14, ''), audio_bitrate),
    transcode_preset_mode = COALESCE(NULLIF($15, ''), transcode_preset_mode),
    video_output_format = COALESCE(NULLIF($16, ''), video_output_format),
    updated_at = NOW(),
    updated_by = $17
WHERE id = 1
RETURNING id, max_file_size_bytes, weekly_upload_limit_bytes, video_storage_path, use_gpu_transcoding, gpu_device_id, nvenc_preset, nvenc_cq, nvenc_rate_control, nvenc_max_bitrate, nvenc_buffer_size, cpu_preset, cpu_crf, max_resolution, audio_bitrate, transcode_preset_mode, video_output_format, updated_at, updated_by
`

type UpdateConfigParams struct {
	MaxFileSizeBytes       int64       `json:"max_file_size_bytes"`
	WeeklyUploadLimitBytes int64       `json:"weekly_upload_limit_bytes"`
	Column3                interface{} `json:"column_3"`
	UseGpuTranscoding      bool        `json:"use_gpu_transcoding"`
	GpuDeviceID            int32       `json:"gpu_device_id"`
	Column6                interface{} `json:"column_6"`
	NvencCq                int32       `json:"nvenc_cq"`
	Column8                interface{} `json:"column_8"`
	Column9                interface{} `json:"column_9"`
	Column10               interface{} `json:"column_10"`
	Column11               interface{} `json:"column_11"`
	CpuCrf                 int32       `json:"cpu_crf"`
	Column13               interface{} `json:"column_13"`
	Column14               interface{} `json:"column_14"`
	Column15               interface{} `json:"column_15"`
	Column16               interface{} `json:"column_16"`
	UpdatedBy              pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) (Config, error) {
	row := q.db.QueryRow(ctx, updateConfig,
		arg.MaxFileSizeBytes,
		arg.WeeklyUploadLimitBytes,
		arg.Column3,
		arg.UseGpuTranscoding,
		arg.GpuDeviceID,
		arg.Column6,
		arg.NvencCq,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.CpuCrf,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
		arg.UpdatedBy,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.MaxFileSizeBytes,
		&i.WeeklyUploadLimitBytes,
		&i.VideoStoragePath,
		&i.UseGpuTranscoding,
		&i.GpuDeviceID,
		&i.NvencPreset,
		&i.NvencCq,
		&i.NvencRateControl,
		&i.NvencMaxBitrate,
		&i.NvencBufferSize,
		&i.CpuPreset,
		&i.CpuCrf,
		&i.MaxResolution,
		&i.AudioBitrate,
		&i.TranscodePresetMode,
		&i.VideoOutputFormat,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
