/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterTokenRouteImport } from './routes/register.$token'
import { Route as AuthUploadRouteImport } from './routes/_auth/upload'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users.index'
import { Route as AuthCategoriesIndexRouteImport } from './routes/_auth/categories.index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin.index'
import { Route as AuthVShortIdRouteImport } from './routes/_auth/v.$shortId'
import { Route as AuthProfileUsernameRouteImport } from './routes/_auth/profile.$username'
import { Route as AuthCategoriesSlugRouteImport } from './routes/_auth/categories.$slug'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin.users'
import { Route as AuthAdminSettingsRouteImport } from './routes/_auth/admin.settings'
import { Route as AuthAdminInvitationsRouteImport } from './routes/_auth/admin.invitations'
import { Route as AuthAdminCategoriesRouteImport } from './routes/_auth/admin.categories'
import { Route as AuthProfileUsernameIndexRouteImport } from './routes/_auth/profile.$username.index'
import { Route as AuthProfileUsernamePlaylistIdRouteImport } from './routes/_auth/profile.$username.playlist.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTokenRoute = RegisterTokenRouteImport.update({
  id: '/register/$token',
  path: '/register/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUploadRoute = AuthUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesIndexRoute = AuthCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthVShortIdRoute = AuthVShortIdRouteImport.update({
  id: '/v/$shortId',
  path: '/v/$shortId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileUsernameRoute = AuthProfileUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AuthProfileRoute,
} as any)
const AuthCategoriesSlugRoute = AuthCategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminSettingsRoute = AuthAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminInvitationsRoute = AuthAdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminCategoriesRoute = AuthAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthProfileUsernameIndexRoute =
  AuthProfileUsernameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthProfileUsernameRoute,
  } as any)
const AuthProfileUsernamePlaylistIdRoute =
  AuthProfileUsernamePlaylistIdRouteImport.update({
    id: '/playlist/$id',
    path: '/playlist/$id',
    getParentRoute: () => AuthProfileUsernameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRouteWithChildren
  '/upload': typeof AuthUploadRoute
  '/register/$token': typeof RegisterTokenRoute
  '/admin/categories': typeof AuthAdminCategoriesRoute
  '/admin/invitations': typeof AuthAdminInvitationsRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/categories/$slug': typeof AuthCategoriesSlugRoute
  '/profile/$username': typeof AuthProfileUsernameRouteWithChildren
  '/v/$shortId': typeof AuthVShortIdRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/categories': typeof AuthCategoriesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/profile/$username/': typeof AuthProfileUsernameIndexRoute
  '/profile/$username/playlist/$id': typeof AuthProfileUsernamePlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRouteWithChildren
  '/upload': typeof AuthUploadRoute
  '/register/$token': typeof RegisterTokenRoute
  '/admin/categories': typeof AuthAdminCategoriesRoute
  '/admin/invitations': typeof AuthAdminInvitationsRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/categories/$slug': typeof AuthCategoriesSlugRoute
  '/v/$shortId': typeof AuthVShortIdRoute
  '/admin': typeof AuthAdminIndexRoute
  '/categories': typeof AuthCategoriesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/profile/$username': typeof AuthProfileUsernameIndexRoute
  '/profile/$username/playlist/$id': typeof AuthProfileUsernamePlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/profile': typeof AuthProfileRouteWithChildren
  '/_auth/upload': typeof AuthUploadRoute
  '/register/$token': typeof RegisterTokenRoute
  '/_auth/admin/categories': typeof AuthAdminCategoriesRoute
  '/_auth/admin/invitations': typeof AuthAdminInvitationsRoute
  '/_auth/admin/settings': typeof AuthAdminSettingsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/categories/$slug': typeof AuthCategoriesSlugRoute
  '/_auth/profile/$username': typeof AuthProfileUsernameRouteWithChildren
  '/_auth/v/$shortId': typeof AuthVShortIdRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/categories/': typeof AuthCategoriesIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/profile/$username/': typeof AuthProfileUsernameIndexRoute
  '/_auth/profile/$username/playlist/$id': typeof AuthProfileUsernamePlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/upload'
    | '/register/$token'
    | '/admin/categories'
    | '/admin/invitations'
    | '/admin/settings'
    | '/admin/users'
    | '/categories/$slug'
    | '/profile/$username'
    | '/v/$shortId'
    | '/admin/'
    | '/categories'
    | '/users'
    | '/profile/$username/'
    | '/profile/$username/playlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/upload'
    | '/register/$token'
    | '/admin/categories'
    | '/admin/invitations'
    | '/admin/settings'
    | '/admin/users'
    | '/categories/$slug'
    | '/v/$shortId'
    | '/admin'
    | '/categories'
    | '/users'
    | '/profile/$username'
    | '/profile/$username/playlist/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_auth/admin'
    | '/_auth/dashboard'
    | '/_auth/profile'
    | '/_auth/upload'
    | '/register/$token'
    | '/_auth/admin/categories'
    | '/_auth/admin/invitations'
    | '/_auth/admin/settings'
    | '/_auth/admin/users'
    | '/_auth/categories/$slug'
    | '/_auth/profile/$username'
    | '/_auth/v/$shortId'
    | '/_auth/admin/'
    | '/_auth/categories/'
    | '/_auth/users/'
    | '/_auth/profile/$username/'
    | '/_auth/profile/$username/playlist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RegisterTokenRoute: typeof RegisterTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$token': {
      id: '/register/$token'
      path: '/register/$token'
      fullPath: '/register/$token'
      preLoaderRoute: typeof RegisterTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/upload': {
      id: '/_auth/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthUploadRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories/': {
      id: '/_auth/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthCategoriesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/v/$shortId': {
      id: '/_auth/v/$shortId'
      path: '/v/$shortId'
      fullPath: '/v/$shortId'
      preLoaderRoute: typeof AuthVShortIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/$username': {
      id: '/_auth/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthProfileUsernameRouteImport
      parentRoute: typeof AuthProfileRoute
    }
    '/_auth/categories/$slug': {
      id: '/_auth/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof AuthCategoriesSlugRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/settings': {
      id: '/_auth/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthAdminSettingsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/invitations': {
      id: '/_auth/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AuthAdminInvitationsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/categories': {
      id: '/_auth/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthAdminCategoriesRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/profile/$username/': {
      id: '/_auth/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof AuthProfileUsernameIndexRouteImport
      parentRoute: typeof AuthProfileUsernameRoute
    }
    '/_auth/profile/$username/playlist/$id': {
      id: '/_auth/profile/$username/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/profile/$username/playlist/$id'
      preLoaderRoute: typeof AuthProfileUsernamePlaylistIdRouteImport
      parentRoute: typeof AuthProfileUsernameRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminCategoriesRoute: typeof AuthAdminCategoriesRoute
  AuthAdminInvitationsRoute: typeof AuthAdminInvitationsRoute
  AuthAdminSettingsRoute: typeof AuthAdminSettingsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminCategoriesRoute: AuthAdminCategoriesRoute,
  AuthAdminInvitationsRoute: AuthAdminInvitationsRoute,
  AuthAdminSettingsRoute: AuthAdminSettingsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthProfileUsernameRouteChildren {
  AuthProfileUsernameIndexRoute: typeof AuthProfileUsernameIndexRoute
  AuthProfileUsernamePlaylistIdRoute: typeof AuthProfileUsernamePlaylistIdRoute
}

const AuthProfileUsernameRouteChildren: AuthProfileUsernameRouteChildren = {
  AuthProfileUsernameIndexRoute: AuthProfileUsernameIndexRoute,
  AuthProfileUsernamePlaylistIdRoute: AuthProfileUsernamePlaylistIdRoute,
}

const AuthProfileUsernameRouteWithChildren =
  AuthProfileUsernameRoute._addFileChildren(AuthProfileUsernameRouteChildren)

interface AuthProfileRouteChildren {
  AuthProfileUsernameRoute: typeof AuthProfileUsernameRouteWithChildren
}

const AuthProfileRouteChildren: AuthProfileRouteChildren = {
  AuthProfileUsernameRoute: AuthProfileUsernameRouteWithChildren,
}

const AuthProfileRouteWithChildren = AuthProfileRoute._addFileChildren(
  AuthProfileRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthProfileRoute: typeof AuthProfileRouteWithChildren
  AuthUploadRoute: typeof AuthUploadRoute
  AuthCategoriesSlugRoute: typeof AuthCategoriesSlugRoute
  AuthVShortIdRoute: typeof AuthVShortIdRoute
  AuthCategoriesIndexRoute: typeof AuthCategoriesIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthProfileRoute: AuthProfileRouteWithChildren,
  AuthUploadRoute: AuthUploadRoute,
  AuthCategoriesSlugRoute: AuthCategoriesSlugRoute,
  AuthVShortIdRoute: AuthVShortIdRoute,
  AuthCategoriesIndexRoute: AuthCategoriesIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RegisterTokenRoute: RegisterTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
